name: Two Aces Realty
favicon: null
layout_spectrum: 0.747364167124033
typography_spectrum: 0.11800362332724035
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.6773842803668231
  lightness: 0.25558261340484023
  saturation: 0.10369770298711956
  rhythmicContrast: 0.48330846312455833
purpose: []
